name: Test build

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test Site Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: true

      - uses: taiki-e/install-action@v2
        with:
          tool: zola@0.21.0

      - name: Build Zola site
        run: zola build
